version: 2.1

orbs:
  matlab: mathworks/matlab@0.4.0

jobs:
  build:
    working_directory: ~/project
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - cache4
      - run: git clone https://github.com/plotly/plotly_matlab.git --branch=master --depth=1
      - run: git clone https://github.com/kakearney/boundedline-pkg.git --branch=master --depth=1
      - run: git clone https://github.com/alchemyst/ternplot.git --branch=master --depth=1
      - run: git clone https://github.com/fangq/jdata.git --branch=master --depth=1
      - checkout
      - matlab/install
      - save_cache:
          key: cache4
          paths:
            - "/usr/local/lib/R/site-library"
      - run:
          command: |
            sudo apt-get install tree
            tree
      - matlab/run-command:
          command: addpath(genpath('plotly_matlab/plotly/')); addpath(genpath('boundedline-pkg/')); addpath(genpath('ternplot/')); addpath(genpath('jdata/')); evalMD;
      - run:
          command: |
            tree

      - run:
          name: Compress Artifacts
          command: tar -cvzf tempF.tar tempF/
      - store_artifacts:
          path: tempF.tar
          destination: artifact-file