version: 2.1

orbs:
  matlab: mathworks/matlab@0.4.0

jobs:
  build:
    working_directory: ~/project
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
        name: Convert raw docs to Jekyll-ready markdown
        command: evalMD