version: 2.1

orbs:
  matlab: mathworks/matlab@0.4.0

jobs:
  build:
    working_directory: ~/project
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - cache4
      - run: git clone https://github.com/plotly/plotly_matlab.git --branch=master --depth=1
      - run: git clone https://github.com/kakearney/boundedline-pkg.git --branch=master --depth=1
      - run: git clone https://github.com/alchemyst/ternplot.git --branch=master --depth=1
      - run: git clone https://github.com/fangq/jdata.git --branch=master --depth=1
      - checkout
      - matlab/install
      - save_cache:
          key: cache4
          paths:
            - "/usr/local/lib/R/site-library"
      - run:
          command: |
            sudo apt-get install tree
            tree
      - matlab/run-command:
          command: addpath(genpath('plotly_matlab/plotly/')); addpath(genpath('boundedline-pkg/')); addpath(genpath('ternplot/')); addpath(genpath('jdata/')); evalMD;
      - run:
          command: |
            tree
      - run:
          name: Compress Artifacts
          command: tar -cvzf tempF.tar tempF/
      - store_artifacts:
          path: tempF.tar
          destination: artifact-file
      - run:
          name: build site and perform front-matter checks
          command: |
            echo ${mapbox_token} > .mapbox_token
            python3 -m venv venv
            . venv/bin/activate
            pip3 install python-frontmatter
            curl https://raw.githubusercontent.com/plotly/graphing-library-docs/master/front-matter-ci.py > front-matter-ci.py
            python front-matter-ci.py matlab
            curl https://raw.githubusercontent.com/plotly/graphing-library-docs/master/check-or-enforce-order.py > check-or-enforce-order.py
            python check-or-enforce-order.py matlab enforce
      - run:
          name: deploy to plotly/plotly.matlab-docs:built
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cd matlab
              git init
              git config user.name plotlydocbot
              git config user.email accounts@plot.ly
              rm -rf *.html
              sed -i.bkp 's/<!--.*-->//g' *md && rm *.bkp # remove html comments
              sed -z -i.bkp 's/```{=html}\n<div/<div/g' *md && rm *.bkp # remove html backticks
              sed -z -i.bkp 's/script>\n```/script>/g' *md && rm *.bkp # remove html backticks
              git add *
              git commit -m "build of https://github.com/plotly/plotly.matlab-docs/commit/${CIRCLE_SHA1}"
              git push --force git@github.com:plotly/plotly.matlab-docs.git master:built
              rm -rf .git
            fi
      # - run:
      #     name: trigger plotly/graphing-library-docs build
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #         git clone --depth=1 git@github.com:plotly/graphing-library-docs.git
      #         cd graphing-library-docs
      #         git config user.name plotlydocbot
      #         git config user.email accounts@plot.ly
      #         git commit --allow-empty -m "deploying https://github.com/plotly/plotly.matlab-docs/commit/${CIRCLE_SHA1}"
      #         git push
      #         cd ..
      #         rm -rf graphing-library-docs
      #       fi
