version: 2.1

orbs:
  matlab: mathworks/matlab@0.4.0

jobs:
  build:
    working_directory: ~/project
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
        command: evalMD


https://uk.mathworks.com/login?uri=https%3A%2F%2Fuk.mathworks.com%2Fmatlabcentral%2Ffileexchange%2F33381-jsonlab-a-toolbox-to-encode-decode-json-files&form_type=community
https://uk.mathworks.com/matlabcentral/fileexchange/33381-jsonlab-a-toolbox-to-encode-decode-json-files