version: 2.1

orbs:
  matlab: mathworks/matlab@0.4.0

  jobs:
    build:
      machine:
        image: 'ubuntu-1604:201903-01'
      steps:
        - run:
          name: install MATLAB
          command:
            - checkout
            - matlab/install
        - run:
          name: build the docs
          command:
            - matlab/run-command:
                command: evalMD
