version: 2.1

orbs:
  matlab: mathworks/matlab@0.4.0

jobs:
  build:
    working_directory: ~/project
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - cache4
      - run: 
          name: Install dependencies
          comnand: |
            git clone https://github.com/plotly/plotly_matlab.git --branch=master --depth=1
      - checkout
      - matlab/install
      - save_cache:
          key: cache4
          paths:
            - "/usr/local/lib/R/site-library"
      - run:
          name: DEBUG - repo structure
          command: |
            sudo apt-get install tree
            tree
      - matlab/run-command:
          command: evalMD;
